### ISSUE TITLE
Wrong documentations

### ISSUE THREAD

**Issue by RettentoRectangle** [iliubinskii/eslint-plugin-misc#4]
Ooops. :)

restrict-identifier-characters: [prefer-const-require](https://iliubinskii.github.io/eslint-plugin-misc/prefer-const-require.html)
typescript/prefer-array-type-alias: [typescript/no-unsafe-object-assign](https://iliubinskii.github.io/eslint-plugin-misc/typescript/no-unsafe-object-assign.html)

**Comment by iliubinskii** [comment]
Thx, fixed:
https://iliubinskii.github.io/eslint-plugin-misc/restrict-identifier-characters.html
https://iliubinskii.github.io/eslint-plugin-misc/typescript/prefer-array-type-alias.html
