### ISSUE TITLE
v1.11.1 - Conflicting peer dependency: @typescript-eslint/utils@5.62.0

### ISSUE THREAD

**Issue by RettentoRectangle** [iliubinskii/eslint-plugin-misc#5]
After upgrading to v1.11.1 we got this error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: xxx
npm ERR! Found: eslint-plugin-misc@1.11.0
npm ERR! node_modules/eslint-plugin-misc
npm ERR!   dev eslint-plugin-misc@"^1.11.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev eslint-plugin-misc@"^1.11.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @typescript-eslint/utils@5.62.0
npm ERR! node_modules/@typescript-eslint/utils
npm ERR!   peer @typescript-eslint/utils@"^5.6.2" from eslint-plugin-misc@1.11.1
npm ERR!   node_modules/eslint-plugin-misc
npm ERR!     dev eslint-plugin-misc@"^1.11.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

You changed your peerDependencies at here:
https://github.com/iliubinskii/eslint-plugin-misc/commit/40a03ebad5aa4780de6e5ba0931c1aed64e48fc7

from
"@typescript-eslint/parser": ">=5",
"@typescript-eslint/utils": ">=5",
"typescript": ">=5",
"vue-eslint-parser": ">=9"

to
"@typescript-eslint/parser": "^5.6.2",
"@typescript-eslint/utils": "^5.6.2",
"typescript": "^5.1.6",
"vue-eslint-parser": "^9.3.1"

In our package.json:
"devDependencies:" {
  "typescript": "^5.2.2",
  "@typescript-eslint/eslint-plugin": "^5.61.0",
  "@typescript-eslint/parser": "^5.61.0",
}

----------

I hope this helps. :)

**Comment by iliubinskii** [comment]
I changed dependencies to:
```
        "@typescript-eslint/parser": "^5",
        "@typescript-eslint/utils": "^5",
        "typescript": "^5",
        "vue-eslint-parser": "^9"
```

If it does not help, you can override dependencies in package.json like this:
```
  "overrides": {
    "eslint-plugin-misc": {
      "<dependency>": "<version>"
    }
  }
```

**Comment by RettentoRectangle** [comment]
Meanwhile we upgraded to typescript-eslint v6, but overrides resolved our problem:
"overrides": {
    "eslint-plugin-misc": {
      "@typescript-eslint/parser": "^6",
      "@typescript-eslint/utils": "^6"
    }
  }

Thanks!
