### ISSUE TITLE
Eslint 9 support

### ISSUE THREAD

**Issue by KristjanTammekivi** [iliubinskii/eslint-plugin-misc#6]
Hi, I get the following error when trying to use this plugin with eslint 9

TypeError: Error while loading rule 'misc/no-index-import': context.getScope is not a function

When trying it with fixupPluginRules helper it says rule misc/no-index-import requires type information (which is the first rule in my config, I assume everything would get that error)

**Comment by iliubinskii** [comment]
I have removed `context.getScope` in the last version. Try now.

> When trying it with fixupPluginRules helper it says rule misc/no-index-import requires type information

This plugin is based on @typescript-eslint/parser. You can use this in your ESLint configs:
```
 parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: { jsx: true },
    ecmaVersion: 2020,
    project: "tsconfig.json",
    sourceType: "module"
  },
```
